[package]
name = "wrap-blocking-attr"
version = "0.1.0"
edition = "2024"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
wrap-blocking-attr-impl = { workspace = true }

[lints]
workspace = true
