[package]
name = "file-suite-common"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
log-level-cli = { version = "0.1.0", path = "../log-level-cli" }

[lints]
workspace = true
