[package]
name = "clap-log-level"
version = "0.1.0"
edition = "2024"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = "4.5.36"
log = "0.4.27"
paste = "1.0.15"

[lints]
workspace = true
