[package]
name = "clap-log-level"
version = "0.1.0"
edition = "2024"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { workspace = true }
log = { workspace = true }
paste = { workspace = true }

[lints]
workspace = true
