[package]
name = "compile-nested"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
color-eyre = "0.6.3"
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.27"
rayon = "1.10.0"
symlink = "0.1.0"
walkdir = "2.5.0"
