[package]
name = "file-suite"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
compile-nested = { workspace = true }
file-suite-common = { workspace = true }
generate-keyfile = { workspace = true }
log.workspace = true
path-is-utf8 = { workspace = true }

[lints]
workspace = true
