[package]
name = "pipe-size"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Axel Lord"]

[dependencies]
bytesize = "2.0.1"
clap = { version = "4.5.36", features = ["derive"] }

[lints]
workspace = true
