[package]
name = "clap-complete-command"
version = "0.1.0"
edition = "2024"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
clap_complete = "4.5.47"
patharg = "0.4.0"
thiserror = "2.0.12"

[lints]
workspace = true
