[package]
name = "fold-tokens"
version = "0.1.0"
edition = "2024"

[dependencies]
tokens-rc = { path = "../tokens-rc/" }
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true

[lints]
workspace = true
